# Generated by Django 5.1.5 on 2025-02-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
