# Generated by Django 5.1.5 on 2025-02-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_labresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabResult',
        ),
    ]
