# Generated by Django 5.1.5 on 2025-02-28 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_labresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('prescription', 'Prescription'), ('lab_result', 'Lab Result')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
