# Generated by Django 5.1.5 on 2025-02-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_medicalfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalfile',
            name='cloudinary_public_id',
        ),
        migrations.RemoveField(
            model_name='medicalfile',
            name='file_url',
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_files/'),
        ),
    ]
