# Generated by Django 5.1.5 on 2025-03-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_medicalfile_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfile',
            name='structured_text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
