# Generated by Django 5.1.5 on 2025-03-28 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_medicalfile_structured_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('observed_value', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=50)),
                ('reference_range', models.CharField(max_length=255)),
                ('medical_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='main.medicalfile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('medical_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.medicalfile')),
            ],
        ),
    ]
