# Generated by Django 5.1.5 on 2025-04-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_investigation_medicalreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('prediction', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
