# Generated by Django 5.1.5 on 2025-04-04 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cancerprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianFoodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
